### PR TITLE
Medical Insurance Cost Prediction Web App using Streamlit

### PR DESCRIPTION
**Pull request by dvamsidhar2002**
Hey! This is a Medical Insurance Cost prediction web app. It is completed project with the ml model deployed as a live website and the link of the website is given in the Readme.md file.

### CODE REVIEW

**Comment by aswintechguy** [comment]
Hey vamsi,
Thanks for sharing the project to the community. I have approved the pull
request. For web app, numeric variables like gender and area can be
represented with drop down in string format. Result also can be displayed
in rupees without list. It will make the project much better for end users
to see. I have a website hackersrealm.net where I will share content for
the videos via text article. If you're interested in content writing.
Please let me know, we can discuss further.

With Regards,
Aswin S

**Comment by dvamsidhar2002** [comment]
Hi ashwin! It is really great to hear from you. I would definitely be interested in content writing. Do let me know what I can do. Thanks for giving me the opportunity.

**Comment by aswintechguy** [comment]
That's good to hear. Please connect via instagram or linkedin so we could
discuss further. Try have a look at the website and the blog to get an idea.

With Regards,
Aswin S

**Comment by dvamsidhar2002** [comment]
That's great can you share your linkedin and insta handles. 
Mine is this : https://www.linkedin.com/in/dvamsidhar5932200802/

https://www.instagram.com/thevamsi2395/

**Comment by aswintechguy** [comment]
It's aswintechguy

**Pull request merged**
